# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Societe_Ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('adresse', models.CharField(max_length=150)),
                ('site_web', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('fax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField(verbose_name='Entre')),
                ('p2', models.IntegerField(verbose_name='Et')),
                ('prix', models.IntegerField(verbose_name='Prix')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Societe_Ta')),
            ],
        ),
    ]
