# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='p1',
            new_name='montant_debut',
        ),
        migrations.RenameField(
            model_name='tarif',
            old_name='p2',
            new_name='montant_fin',
        ),
        migrations.AddField(
            model_name='tarif',
            name='est_international',
            field=models.BooleanField(default=False),
        ),
    ]
