# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_auto_20170619_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Societe_Ta',
            new_name='Societe_Transfert',
        ),
    ]
