# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_auto_20170619_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe_transfert',
            name='nom',
            field=models.CharField(max_length=20, unique=True, verbose_name='Société de transfert'),
        ),
    ]
